version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    working_directory: /apps
    steps:
      - checkout
      - run: sudo apt-get -qq update && sudo apt-get -qq install hugo
      - run: hugo